#!/bin/bash

TOPDIR=$HOME
# ---
PSIKEDSREP=$TOPDIR/gits.remote.net/psikeds
PKBEDITOR=$PSIKEDSREP/KnowledgeBaseEditor/src/psiKedsXtxKrl

PKBXTEMAT=$PKBEDITOR/xte.mat
PKBREFMAT=$PKBEDITOR/pkb.mat

PKBXTXKRL=PsiKedsXtxKrl
PKBXTXDEF=$PKBXTXKRL.xtext
PKBXTXGEN=${PKBXTXKRL}Generator.xtend
# ----
EWSXTX=$TOPDIR/ews.xtx
EWSXTXPKB=$EWSXTX/org.psikeds.kb
EWSXTXPKBDEFDIR=$EWSXTXPKB/src/org/psikeds/kb
EWSXTXPKBCGENDIR=$EWSXTXPKBDEFDIR/modelling/generator

EWSPKB=$TOPDIR/ews.pkb/psikedsLetterEnvelopePostDemo
EWSPKBSRC=$EWSPKB/src
EWSPKBSRCGEN=$EWSPKB/src-gen

PKBREF=psiKedsLetterEnvelope
PKBREFPKB=$PKBREF.pkb
PKBREFXML=$PKBREFPKB.xml


# ---
SRC_PKBDEFFILE=$EWSXTXPKBDEFDIR/$PKBXTXDEF
SRC_PKBCGENFILE=$EWSXTXPKBCGENDIR/$PKBXTXGEN
SRC_PKBREFPKBFILE=$EWSPKBSRC/$PKBREFPKB
SRC_PKBREFXMLFILE=$EWSPKBSRCGEN/$PKBREFXML


TGT_PKBDEFFILE=$PKBXTEMAT/$PKBXTXDEF
TGT_PKBCGENFILE=$PKBXTEMAT/$PKBXTXGEN
TGT_PKBREFPKBFILE=$PKBREFMAT/$PKBREFPKB
TGT_PKBREFXMLFILE=$PKBREFMAT/$PKBREFXML


SAVFILES="$TGT_PKBDEFFILE $TGT_PKBCGENFILE $TGT_PKBREFPKBFILE $TGT_PKBREFXMLFILE"
echo "saving existing target files"
for file in $SAVFILES; do echo $file; if [ -e $file ]; then cp $file $file.sav; fi done
echo "1) cp:XTX.DEF $SRC_PKBDEFFILE => $TGT_PKBDEFFILE"
cp $SRC_PKBDEFFILE $TGT_PKBDEFFILE
echo "2) cp:XTX.CGEN $SRC_PKBCGENFILE => $TGT_PKBCGENFILE"
cp $SRC_PKBCGENFILE $TGT_PKBCGENFILE
echo "3) cp:PKB.REF $SRC_PKBREFPKBFILE => $TGT_PKBREFPKBFILE"
cp $SRC_PKBREFPKBFILE $TGT_PKBREFPKBFILE
echo "4) cp:PKB.XML $SRC_PKBREFXMLFILE => $TGT_PKBREFXMLFILE"
cp $SRC_PKBREFXMLFILE $TGT_PKBREFXMLFILE 
